import unittest
from unittest.mock import AsyncMock, patch, MagicMock
import sys
import os
import json

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from scraper.pipeline import process_scraped_data, process_scraped_json, generate_newsletter

class TestPipeline(unittest.TestCase):
    @patch('scraper.pipeline.boto3.client')
    @patch('scraper.pipeline.categorize_article')
    @patch('scraper.pipeline.generate_two_level_summary')
    @patch('scraper.pipeline.summarize_article')
    def test_pipeline_processing(self, mock_summarize, mock_gen_summary, mock_categorize, mock_s3_client_cls):
        # Mock categorization & summarization
        mock_categorize.return_value = "Zero-Day"
        mock_gen_summary.return_value = {
            "short_summary": "This is a short summary generated by model.",
            "deep_summary": "This is a deeper paragraph structure representing the story."
        }
        mock_summarize.return_value = "CVE summary detail."
        
        # Mock boto3 s3 client
        mock_s3 = MagicMock()
        class MockNoSuchKey(Exception):
            pass
        mock_s3.exceptions.NoSuchKey = MockNoSuchKey
        mock_s3_client_cls.return_value = mock_s3
        
        # Mock download checks for deduplication (NoSuchKey)
        mock_s3.get_object.side_effect = MockNoSuchKey()

        # Sample input data from scraper/v2.py
        input_data = {
            "news": [
                {
                    "title": "Critical vulnerability in system service",
                    "link": "https://example.com/vuln1",
                    "date": "2026-06-26",
                    "content": "This is a relatively long content string that exceeds the minimum character limit of two hundred characters so it can pass the filter check. Detailed description of the router bug goes here. It enables root level console access without credentials."
                }
            ],
            "cves": [
                {
                    "cve_id": "CVE-2026-9999",
                    "description": "Critical bypass vulnerability in auth subsystem.",
                    "severity": "9.8 Critical",
                    "published_date": "2026-06-25T00:00:00Z"
                }
            ]
        }
        
        import asyncio
        try:
            loop = asyncio.get_event_loop()
        except RuntimeError:
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            
        status = loop.run_until_complete(process_scraped_data(input_data))
        
        self.assertEqual(status["scrape"], "success")
        self.assertEqual(status["stories"], 1)
        
        # Check that put_object was called to save latest.json and daily issues
        mock_s3.put_object.assert_called()

    def test_generate_newsletter(self):
        sample_json = {
            "date": "2026-06-26",
            "top_stories": [
                {
                    "title": "Severe RCE in Middleware",
                    "short_summary": "A critical RCE affects the portal.",
                    "deep_summary": "A deep analysis of the critical RCE.",
                    "category": "Zero-Day",
                    "score": 10,
                    "url": "https://example.com"
                }
            ],
            "cves": [
                {
                    "title": "Vulnerability CVE-2026-1234",
                    "summary": "AI description of CVE.",
                    "cve_ids": ["CVE-2026-1234"]
                }
            ]
        }
        
        text = generate_newsletter(sample_json)
        self.assertIn("Severe RCE in Middleware", text)
        self.assertIn("A critical RCE affects the portal.", text)
        self.assertIn("CVE-2026-1234", text)

if __name__ == "__main__":
    unittest.main()
